"""Verify the calendar register without silently accepting changed files."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGISTER = ROOT / 'production/assets.json'
SUFFIXES = {'.png', '.jpg', '.jpeg', '.webp', '.svg', '.pdf', '.json'}
FOLDERS = ['characters', 'calender-images-v0', 'back-images-with-puzzles-v1', 'drafts', 'publisher_mark', 'production/puzzles', 'output']


def digest(path):
    h = hashlib.sha256()
    with path.open('rb') as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b''):
            h.update(chunk)
    return h.hexdigest()


def inventory():
    return {p.name for p in ROOT.glob('*.pdf')} | {p.relative_to(ROOT).as_posix() for folder in FOLDERS
            for p in (ROOT / folder).rglob('*')
            if p.is_file() and p.suffix.lower() in SUFFIXES
            and 'render' not in p.parts and '__pycache__' not in p.parts}


def check(data):
    errors, seen = [], set()
    for key, asset in data['assets'].items():
        rel = asset['path']
        path = (ROOT / rel).resolve()
        if not path.is_relative_to(ROOT) or Path(rel).is_absolute():
            errors.append(f'{key}: invalid local path'); continue
        if rel in seen:
            errors.append(f'{key}: duplicate path {rel}')
        seen.add(rel)
        if not path.is_file():
            errors.append(f'{key}: missing {rel}')
        elif digest(path) != asset['sha256']:
            errors.append(f'{key}: checksum differs {rel}')
        for field in ['role', 'design_status', 'print_status', 'issues', 'origin', 'usage']:
            if field not in asset:
                errors.append(f'{key}: missing {field}')
    for key in data.get('selection', {}).values():
        if key not in data['assets']:
            errors.append(f'Unknown selection: {key}')
        elif data['assets'][key]['design_status'] in {'reference_only', 'rejected'}:
            errors.append(f'Blocked selection: {key}')
    for rel in sorted(inventory() - seen):
        errors.append(f'Unregistered: {rel}')
    return errors


def overview(data, errors):
    lines = ['# Asset-Liste und Produktionsstatus', '',
             '<!-- Generated by tools/check-production-assets.py; edit assets.json. -->', '',
             f"Erfasst: {len(data['assets'])} Dateien. Prüffehler: {len(errors)}.", '',
             'Prüfsummenprüfung ist keine Sichtprüfung oder Druckfreigabe.', '',
             'Etsy/Gelato-Kalender 2027: Arbeitsstände, keine Druckfreigabe.', '',
             '## Offene Projektpunkte', '']
    lines += [f'- {v}' for v in data.get('issues', {}).values()]
    if errors:
        lines += ['', '## Prüffehler', ''] + [f'- {e}' for e in errors]
    lines += ['', '## Dateien', '', '| ID | Datei | Verwendung | Gestaltung | Druck | Offene Punkte |',
              '|---|---|---|---|---|---|']
    for key, a in data['assets'].items():
        issue = '; '.join(a['issues']) or '—'
        lines.append(f"| {key} | [{a['path']}](../{a['path']}) | {a['usage']} | {a['design_status']} | {a['print_status']} | {issue} |")
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--write-overview', action='store_true')
    args = parser.parse_args()
    data = json.loads(REGISTER.read_text())
    errors = check(data)
    if args.write_overview:
        (ROOT / 'production/STATUS.md').write_text(overview(data, errors))
    print(f"{len(data['assets'])} assets; {len(errors)} errors")
    for error in errors:
        print(error)
    raise SystemExit(bool(errors))
